# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Quicknote < Formula
  desc ""
  homepage "https://github.com/ramseskamanda/quicknote"
  version "0.1.1"

  on_macos do
    url "https://github.com/ramseskamanda/quicknote/releases/download/v0.1.1/quicknote_0.1.1_darwin_all.tar.gz"
    sha256 "c2d7d6b6155c6845568400cf0ffaa93e5da30df7c81d9f3c374e0c180b9330b6"

    def install
      bin.install "quicknote"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ramseskamanda/quicknote/releases/download/v0.1.1/quicknote_0.1.1_linux_arm64.tar.gz"
      sha256 "cd57e78812354f74f6567801291435601b0d6cb11e67b1217608b7afa603441a"

      def install
        bin.install "quicknote"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ramseskamanda/quicknote/releases/download/v0.1.1/quicknote_0.1.1_linux_amd64.tar.gz"
      sha256 "486ecb7a30dbb88d5e0482e9d51003d327c9bb06370662ca35597b91a0e94174"

      def install
        bin.install "quicknote"
      end
    end
  end
end
